### ISSUE TITLE
[README.md] Mention that `EDITOR` may be set locally (on Linux ?)

### ISSUE THREAD

**Issue by Kr1ss-XD** [dandavison/open-in-editor#4]
I noticed README.md states in the "Installation" paragraph :

>Ensure that one of the environment variables OPEN_IN_EDITOR or EDITOR contains a path to an executable that open-in-editor is going to recognize. **This environment variable must be set system-wide, not just in your shell process.**

At least regarding Linux, this is not correct.

```
$ echo $FOO  # (unset)

$ python -c 'import os; print(os.getenv("FOO"))'
None
$ FOO=bar python -c 'import os; print(os.getenv("FOO"))'
bar
```

The results are the same with Python 3.8.5 and 2.7.18 btw.

**EDIT:** Interestingly, I do yield the same results using Python 3.8.2 as well as 2.7.16 in a (Catalina) Mac VM. Maybe the behavior described in the README was specific to some older version(s) of the Python libraries and has since been changed ?

**Comment by dandavison** [comment]
> This environment variable must be set system-wide, not just in your shell process.

The docs say this because the Python script is launched by an OS mechanism and ends up not being a child process of the user shell process.
